stages:
  predeploy:
    - prepare
  dev:
    - dry-run
    - deploy
    

variables:
  VERSION: v0.0.1
  NAMESPACE: test
  HELM_NAME: test-scheduler
  HELM_NAMESPACE: test
  HELM_CHART: helm/
  HELM_CHART_VERSION: 0.1.1
  GIT_PROVIDER: github
  GIT_CREDENTIAL: github
  TEST_CLUSTER_NAME: dev
  DEPLOY_CLUSTER_NAME: dev
  SERVICE_NAME: scheduler
  SERVICE_URL: scheduler.$NAMESPACE.ankra.app

dev:
  target:
    match:
      name: $DEPLOY_CLUSTER_NAME
  dry-run:
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    helm:
      - action: upgrade
        build_dependencies: true
        name: csi-s3
        namespace: kube-system
        chart: $WORKSPACE/deploy/helm
        extra_args:
          -  --set secret.accessKey=$AWS_ACCESS_KEY_ID
          - --set secret.secretKey=$AWS_SECRET_ACCESS_KEY
          - --set secret.endpoint=https://s3.eu-central-1.amazonaws.com
          - --dry-run
  deploy:
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    helm:
      - action: upgrade
        build_dependencies: true
        name: csi-s3
        namespace: kube-system
        chart: $WORKSPACE/deploy/helm
        extra_args:
          -  --set secret.accessKey=$AWS_ACCESS_KEY_ID
          - --set secret.secretKey=$AWS_SECRET_ACCESS_KEY
          - --set secret.endpoint=https://s3.eu-central-1.amazonaws.com